[package]
name = "pretty-exec-lib"
description = "Print a command and then execute it"
version = "0.0.37"
authors = ["khai96_ <hvksmr1996@gmail.com>"]
license = "MIT"
edition = "2018"
keywords = ["spawn", "subprocess", "command"]
repository = "https://github.com/KSXGitHub/pretty-exec.git"
readme = "README.md"

[dependencies]
ansi_term = "^0.12.1"
shell-escape = "^0.1.5"
structopt = "^0.3.26"
structopt-utilities = "^0.1.0"
pipe-trait = "^0.3.2"
