complete -c pretty-exec -n "__fish_use_subcommand" -l color -d 'When to use color [choices: auto, never, always]'
complete -c pretty-exec -n "__fish_use_subcommand" -l skip-exec -d 'Do not execute, print command only'
complete -c pretty-exec -n "__fish_use_subcommand" -l github-actions -d 'Enable GitHub Action grouping'
complete -c pretty-exec -n "__fish_use_subcommand" -s h -l help -d 'Prints help information'
complete -c pretty-exec -n "__fish_use_subcommand" -s V -l version -d 'Prints version information'
