[package]
name = "pretty-exec"
description = "Print a command and then execute it"
version = "0.0.13"
authors = ["khai96_ <hvksmr1996@gmail.com>"]
license = "MIT"
edition = "2018"
keywords = ["spawn", "subprocess", "command"]
categories = ["command-line-utilities"]
repository = "https://github.com/KSXGitHub/pretty-exec.git"

[dependencies.pretty-exec-lib]
version = "0.0.13"
path = "../pretty-exec-lib"

[dev-dependencies]
ansi_term = "^0.12.1"
toml = "^0.5.6"
serde_json = "^1.0.53"
pipe-trait = "^0.1.11"

[dev-dependencies.serde]
version = "^1.0.110"
features = ["derive"]
